### ISSUE TITLE
no longer consistently bypasses overseas block

### ISSUE THREAD

**Issue by hoppypaw** [foomango/bypass-taobao-overseas-block#2]
at times, the popup asking to leave the page will fail to appear, leading to the overseas block page replacing the taobao/tmall link
https://item.taobao.com/item.htm?id=655700329471 example of an item blocked for overseas shipment
seems completely random as to when the popup will fail to appear

**Comment by foomango** [comment]
@revvydin In order to show the second popup, please click on the page as quickly as possible after the first popup is gone.

**Comment by hoppypaw** [comment]
thanks, sometimes i still miss and the page redirects but it's nice to know there's a workaround now :)

**Comment by qwuae1** [comment]
can we make that process auto...
the page still redirects more of the time...
